apiVersion: v1
kind: Service
metadata:
  name: encontros-tech
  labels:
    app: encontros-tech
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: encontros-tech
